# Generated by Django 6.0.3 on 2026-03-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_evaluationrubricdefinition_instructiondefinition_and_more'),
        ('conversations', '0002_alter_conversationsession_evaluation_rubric_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptComponent',
        ),
    ]
