# Generated by Django 6.0.3 on 2026-03-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversationsession_evaluation_rubric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrun',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='conversationturn',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='agentrun',
            old_name='input_payload',
            new_name='payload',
        ),
        migrations.RenameField(
            model_name='agentrun',
            old_name='output_payload',
            new_name='telemetry',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='latency_ms',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='status',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='tokens_in',
        ),
        migrations.RemoveField(
            model_name='agentrun',
            name='tokens_out',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='latest_metrics',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='started_at',
        ),
        migrations.AddField(
            model_name='agentrun',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='role',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluida'), ('archived', 'Arquivada')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversationturn',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('doctor_simulator', 'Medico simulado'), ('system', 'Sistema')], max_length=32),
        ),
        migrations.DeleteModel(
            name='ConversationArtifact',
        ),
    ]
